#!/usr/bin/ruby -Ku

except_words = [
  {:kanji => "三", :kana => "ミ"},
  {:kanji => "訓", :kana => "ン"},
  {:kanji => "君", :kana =>	"ン"},
  {:kanji => "空", :kana => "ウ"},
  {:kanji => "山", :kana => "ヤマ"},
  {:kanji => "槍", :kana => "ヤリ"},
  {:kanji => "泰", :kana => "ヤス"},
  {:kanji => "安", :kana => "ヤス"},
  {:kanji => "義", :kana => "ヨシ"},
  {:kanji => "美", :kana => "ヨシ"},
  {:kanji => "吉", :kana => "ヨシ"},
  {:kanji => "淑", :kana => "ヨシ"},
  {:kanji => "恭", :kana => "ユキ"},
  {:kanji => "雪", :kana => "ユキ"},
  {:kanji => "合", :kana => "アイ"},
  {:kanji => "赤", :kana => "アカ"},
  {:kanji => "明", :kana => "アキ"},
  {:kanji => "雨", :kana => "アマ"},
  {:kanji => "天", :kana => "アマ"},
  {:kanji => "行", :kana => "アン"},
  {:kanji => "麻", :kana => "アサ"},
  {:kanji => "当", :kana => "アテ"},
  {:kanji => "原", :kana => "バラ"},
  {:kanji => "針", :kana => "バリ"},
  {:kanji => "橋", :kana => "バシ"},
  {:kanji => "鳩", :kana => "バト"},
  {:kanji => "紅", :kana => "ベニ"},
  {:kanji => "星", :kana => "ボシ"},
  {:kanji => "棚", :kana => "ダナ"},
  {:kanji => "寺", :kana => "デラ"},
  {:kanji => "年", :kana => "ドシ"},
  {:kanji => "川", :kana => "ガワ"},
  {:kanji => "越", :kana => "ゴシ"},
  {:kanji => "毎", :kana => "ゴト"},
  {:kanji => "花", :kana => "ハナ"},
  {:kanji => "原", :kana => "ハラ"},
  {:kanji => "腹", :kana => "ハラ"},
  {:kanji => "橋", :kana => "ハシ"},
  {:kanji => "旗", :kana => "ハタ"},
  {:kanji => "蛇", :kana => "ヘビ"},
  {:kanji => "平", :kana => "ヒラ"},
  {:kanji => "広", :kana => "ヒロ"},
  {:kanji => "弘", :kana => "ヒロ"},
  {:kanji => "市", :kana => "イチ"},
  {:kanji => "家", :kana => "イエ"},
  {:kanji => "池", :kana => "イケ"},
  {:kanji => "生", :kana => "イキ"},
  {:kanji => "入", :kana => "イリ"},
  {:kanji => "色", :kana => "イロ"},
  {:kanji => "石", :kana => "イシ"},
  {:kanji => "板", :kana => "イタ"},
  {:kanji => "痛", :kana => "イタ"},
  {:kanji => "島", :kana => "ジマ"},
  {:kanji => "壁", :kana => "カベ"},
  {:kanji => "株", :kana => "カブ"},
  {:kanji => "景", :kana => "カゲ"},
  {:kanji => "上", :kana => "カミ"},
  {:kanji => "仮", :kana => "カリ"},
  {:kanji => "軽", :kana => "カル"},
  {:kanji => "型", :kana => "カタ"},
  {:kanji => "川", :kana => "カワ"},
  {:kanji => "和", :kana => "カズ"},
  {:kanji => "金", :kana => "キム"},
  {:kanji => "北", :kana => "キタ"},
  {:kanji => "越", :kana => "コシ"},
  {:kanji => "組", :kana => "クミ"},
  {:kanji => "窓", :kana => "マド"},
  {:kanji => "孫", :kana => "マゴ"},
  {:kanji => "昌", :kana => "マサ"},
  {:kanji => "正", :kana => "マサ"},
  {:kanji => "三", :kana => "ミツ"},
  {:kanji => "水", :kana => "ミズ"},
  {:kanji => "物", :kana => "モノ"},
  {:kanji => "許", :kana => "モト"},
  {:kanji => "素", :kana => "モト"},
  {:kanji => "元", :kana => "モト"},
  {:kanji => "宗", :kana => "ムネ"},
  {:kanji => "斑", :kana => "ムラ"},
  {:kanji => "村", :kana => "ムラ"},
  {:kanji => "長", :kana => "ナガ"},
  {:kanji => "中", :kana => "ナカ"},
  {:kanji => "生", :kana => "ナマ"},
  {:kanji => "波", :kana => "ナミ"},
  {:kanji => "西", :kana => "ニシ"},
  {:kanji => "徳", :kana => "ノリ"},
  {:kanji => "主", :kana => "ヌシ"},
  {:kanji => "岡", :kana => "オカ"},
  {:kanji => "興", :kana => "オキ"},
  {:kanji => "大", :kana => "オオ"},
  {:kanji => "織", :kana => "オリ"},
  {:kanji => "乙", :kana => "オト"},
  {:kanji => "木", :kana => "ラギ"},
  {:kanji => "定", :kana => "サダ"},
  {:kanji => "里", :kana => "サト"},
  {:kanji => "郷", :kana => "サト"},
  {:kanji => "白", :kana => "シラ"},
  {:kanji => "白", :kana => "シロ"},
  {:kanji => "城", :kana => "シロ"},
  {:kanji => "高", :kana => "タカ"},
  {:kanji => "孝", :kana => "タカ"},
  {:kanji => "武", :kana => "タケ"},
  {:kanji => "竹", :kana => "タケ"},
  {:kanji => "珠", :kana => "タマ"},
  {:kanji => "富", :kana => "トミ"},
  {:kanji => "知", :kana => "トモ"},
  {:kanji => "年", :kana => "トシ"},
  {:kanji => "罪", :kana => "ツミ"},
  {:kanji => "午", :kana => "ウマ"},
  {:kanji => "馬", :kana => "ウマ"},
  {:kanji => "牛", :kana => "ウシ"},
  {:kanji => "割", :kana => "ワリ"},
  {:kanji => "悪", :kana => "ワル"},
  {:kanji => "綿", :kana => "ワタ"},
  {:kanji => "業", :kana => "ワザ"},
  {:kanji => "酒", :kana => "ザケ"},
  {:kanji => "銭", :kana => "ゼニ"},
  {:kanji => "粥", :kana => "カユ"},
  {:kanji => "宮", :kana => "ミヤ"},
  {:kanji => "親", :kana => "オヤ"},
  {:kanji => "倭", :kana => "ヤマト"},
  {:kanji => "胡", :kana => "エビス"},
  {:kanji => "黄", :kana => "ファン"},
  {:kanji => "東", :kana => "ヒガシ"},
  {:kanji => "聖", :kana => "ヒジリ"},
  {:kanji => "光", :kana => "ヒカリ"},
  {:kanji => "丙", :kana => "ヒノエ"},
  {:kanji => "裕", :kana => "ヒロシ"},
  {:kanji => "斉", :kana => "ヒトシ"},
  {:kanji => "沙", :kana => "イサゴ"},
  {:kanji => "甲", :kana => "カブト"},
  {:kanji => "烏", :kana => "カラス"},
  {:kanji => "甲", :kana => "キノエ"},
  {:kanji => "合", :kana => "ミアイ"},
  {:kanji => "南", :kana => "ミナミ"},
  {:kanji => "貪", :kana => "ムサボ"},
  {:kanji => "七", :kana => "ナナク"},
  {:kanji => "日", :kana => "ニホン"},
  {:kanji => "船", :kana => "ロフネ"},
  {:kanji => "幕", :kana => "ロマク"},
  {:kanji => "界", :kana => "サカイ"},
  {:kanji => "制", :kana => "セイク"},
  {:kanji => "芒", :kana => "ススキ"},
  {:kanji => "忠", :kana => "タダシ"},
  {:kanji => "環", :kana => "タマキ"},
  {:kanji => "堤", :kana => "ツツミ"},
  {:kanji => "閏", :kana => "ウルウ"},
  {:kanji => "山", :kana => "ラヤマ"},
  {:kanji => "山", :kana => "リヤマ"},
  {:kanji => "公", :kana => "オオヤケ"},
  {:kanji => "道", :kana => "ミチ"},
  {:kanji => "塩", :kana => "シオ"},
  {:kanji => "麻", :kana => "マー"},
  {:kanji => "間", :kana => "マ"},
  {:kanji => "見", :kana => "ミ"},
  {:kanji => "巻", :kana => "マキ"},
  {:kanji => "光", :kana => "ミツ"},
  {:kanji => "杰", :kana => "モク"},
  {:kanji => "組", :kana => "ク"},
  {:kanji => "子", :kana => "コ"},
  {:kanji => "桂", :kana => "チュウ"},
  {:kanji => "手", :kana => "テ"},
  {:kanji => "身", :kana => "ミ"},
  {:kanji => "松", :kana => "マツ"},
  {:kanji => "腫", :kana => "ミ"},
  {:kanji => "町", :kana => "マチ"},
  {:kanji => "歯", :kana => "ハ"},
  {:kanji => "草", :kana => "ク"},
  {:kanji => "倉", :kana => "ク"},
  {:kanji => "関", :kana => "セキ"},
  {:kanji => "江", :kana => "エ"},
  {:kanji => "本", :kana => "ク"},
  {:kanji => "本", :kana => "コウ"},
  {:kanji => "重", :kana => "エ"},
  {:kanji => "亨", :kana => "ヒョン"},
  {:kanji => "根", :kana => "ネ"},
  {:kanji => "枕", :kana => "マク"},
  {:kanji => "世", :kana => "ヨ"},
  {:kanji => "新", :kana => "ニイ"},
  {:kanji => "小", :kana => "コ"},
  {:kanji => "化", :kana => "ファ"},
  {:kanji => "子", :kana => "ネ"},
  {:kanji => "柱", :kana => "ニチ"},
  {:kanji => "寧", :kana => "ニョン"},
  {:kanji => "日", :kana => "ヒ"},
  {:kanji => "陽", :kana => "ヒ"},
  {:kanji => "日", :kana => "ビ"},
  {:kanji => "魚", :kana =>"ウオ"},
  {:kanji => "潮", :kana =>"シオ"},
  {:kanji => "出", :kana =>"デ"},
  {:kanji => "涅", :kana =>"ネ"},
  {:kanji => "口", :kana =>"グチ"},
  {:kanji => "地", :kana =>"サチ"},
  {:kanji => "音", :kana =>"ネ"},
  {:kanji => "判", :kana =>"ホウ"},
  {:kanji => "韓", :kana =>"コウ"},
  {:kanji => "院", :kana =>"ク"},
  {:kanji => "丹", :kana =>"ニ"},
  {:kanji => "田", :kana =>"タ"},
  {:kanji => "津", :kana =>"ツ"},
  {:kanji => "雀", :kana =>"ジャン"},
  {:kanji => "哲", :kana =>"ショウ"},
  {:kanji => "黒", :kana =>"ク"},
  {:kanji => "目", :kana =>"メ"},
  {:kanji => "作", :kana =>"サ"},
  {:kanji => "劾", :kana =>"ガイ"},
  {:kanji => "作", :kana =>"サ"},
  {:kanji => "種", :kana =>"サ"},
]
tsv_header = ["kanji","kana","kana_parsed","kana_romaji","hangul","hangul_parsed","hangul_romaja","kana_initial_medial","kana_final","kana_romaji_initial","kana_romaji_medial","kana_romaji_final","hangul_initial","hangul_medial","hangul_final","hangul_romaja_initial","hangul_romaja_medial","hangul_romaja_final","oldkana","かな(初声)","かな(中声)","かな(終声)","한글(初声)","한글(中声)","한글(終声)"]

multibyte_label_table_kana_first = {
  "(none)" => "(01) ア行",
  "w" => "(02) ワ行(w)",
  "k" => "(03) カ行(k)",
  "g" => "(04) ガ行(g)",
  "s" => "(05) サ行(s)",
  "t" => "(06) タ行(t)",
  "d" => "(07) ダ行(d)",
  "j" => "(08) ジャ行(j)",
  "z" => "(09) ザ行(z)",
  "n" => "(10) ナ行(n)",
  "b" => "(11) バ行(b)",
  "h" => "(12) ハ行(h)",
  "p" => "(13) パ行(p)",
  "f" => "(14) ファ行(hw)",
  "m" => "(15) マ行(m)",
  "r" => "(16) ラ行(r)",
}

multibyte_label_table_hangul_first = {
  "(none)" => "(01) ㅇ",
  "g" => "(02) ㄱ(g)",
  "h" => "(03) ㅎ(h)",
  "k" => "(04) ㅋ(kh)",
  "s" => "(05) ㅅ(s)",
  "j" => "(06) ㅈ(j)",
  "d" => "(07) ㄷ(d)",
  "ch" => "(08) ㅊ(ch)",
  "t" => "(09) ㅌ(t)",
  "ss" => "(10) ㅆ(ss)",
  "n" => "(11) ㄴ(n)",
  "b" => "(12) ㅂ(b)",
  "m" => "(13) ㅁ(m)",
  "p" => "(14) ㅍ(p)",
  "r" => "(15) ㄹ(r)",
}

multibyte_label_table_hangul_medial = {
  "ae" => "(01) ᅢ(ae)",
  "oe" => "(02) ᅬ(oe)",
  "a" => "(03) ᅡ(a)",
  "wa" => "(04) ᅪ(wa)",
  "o" => "(05) ᅩ(o)",
  "wo" => "(06) ᅯ(wo)",
  "yo" => "(07) ᅭ(yo)",
  "eu" => "(08) ᅳ(eu)",
  "u" => "(09) ᅮ(u)",
  "yu" => "(10) ᅲ(yu)",
  "eo" => "(11) ᅥ(eo)",
  "ya" => "(12) ᅣ(ya)",
  "yeo" => "(13) ᅧ(yeo)",
  "e" => "(14) ᅦ(e)",
  "ye" => "(15) ᅨ(ye)",
  "i" => "(16) ᅵ(i)",
  "ui" => "(17) ᅴ(ui)",
  "wi" => "(18) ᅱ(wi)",
  "we" => "(19) ᅰ(we)",
  "wae" => "(20) ᅫ(wae)",
}

multibyte_label_table_kana_medial = {
  "ai" => "(01) アイ(ai)",
  "a" => "(02) ア(a)",
  "ya" => "(03) ヤ(ya)",
  "w" => "(04) ワ(wa)",
  "o" => "(05) オ(o)",
  "yo" => "(06) ヨ(yo)",
  "u" => "(07) ウ(u)",
  "yu" => "(08) ユ(yu)",
  "e" => "(09) エ(e)",
  "i" => "(10) イ(i)",
  "wa" => "(02) ア(a)",
}

multibyte_label_table_hangul_final ={
  "(none)" => "(01) (none)",
  "ng" => "(02) ㅇ (ng)",
  "b" => "(03) ㅂ (b)",
  "n" => "(04) ㄴ (n)",
  "m" => "(05) ㅁ (m)",
  "k" => "(06) ㄱ (k)",
  "l" => "(07) ㄹ (l)",
}

multibyte_label_table_kana_final = {
  "(none)" => "(01) (none)",
  "u" => "(02) ウ (u)",
  "i" => "(03) イ (i)",
  "n" => "(04) ン (n)",
  "ku" => "(05) ク (ku)",
  "ki" => "(06) キ (ki)",
  "tu" => "(07) ツ (tu)",
  "xtu" => "(08) ッ (xtu)",
  "chi" => "(09) チ (chi)",
}


extracted_records = {}

STDIN.each do |line|
  next if line.length == 1
  # parsing
  record = line.chomp.split(',')
  hangul_parsed = record[5].split('')
  hangul_parsed.push('(none)') if hangul_parsed.length != 3
  hangul_parsed_romaja = record[6].split('-')
  hangul_parsed_romaja[0] = '(none)' if hangul_parsed_romaja[0] == ''
  hangul_parsed_romaja.push('(none)') if hangul_parsed_romaja.length != 3
  kana_parsed = record[2].split('-')
  kana_parsed.push('(none)') if kana_parsed.length != 2
  kana_parsed_romaji = record[3].split('-')
  kana_parsed_romaji.push('(none)') if kana_parsed_romaji.length != 3
  if kana_parsed_romaji[1] == 'a' && kana_parsed_romaji[2] == 'i' then # aiは例外
    kana_parsed_romaji[1] = 'ai'
    kana_parsed_romaji[2] = '(none)'
  end
  if kana_parsed_romaji[0] == 'w' && kana_parsed_romaji[1] == 'a' then # waは例外(あえて両方につける)
    kana_parsed_romaji[0] = 'w'
    kana_parsed_romaji[1] = 'wa'
  end
  kana_parsed_romaji[1] = 'i' if kana_parsed_romaji[1] == 'yi'
  next if except_words.include?({:kanji=>record[0], :kana =>record[1]}) # 例外単語は飛ばす
  next if kana_parsed_romaji.length > 3 # 訓読みは排除
  kana_cons = /[a,i,u,e,o]/ =~ kana_parsed_romaji[0] || kana_parsed_romaji[0].length == 0 ? '(none)' : kana_parsed_romaji[0]
  kana_vowel = kana_parsed_romaji.length != 1 ? kana_parsed_romaji[1] : kana_parsed_romaji[0]
  kana_final = kana_parsed_romaji.length != 1 ? kana_parsed_romaji[-1] : '(none)'
  kana_phenome = [kana_parsed,kana_cons,kana_vowel,kana_final]
  oldkana = record[7]
  multibyte_labeled_kana = [multibyte_label_table_kana_first[kana_cons],multibyte_label_table_kana_medial[kana_vowel],multibyte_label_table_kana_final[kana_final]]
  multibyte_labeled_hangul = [multibyte_label_table_hangul_first[hangul_parsed_romaja[0]],multibyte_label_table_hangul_medial[hangul_parsed_romaja[1]],multibyte_label_table_hangul_final[hangul_parsed_romaja[2]]]
  output_record = [record[0..6],kana_phenome,hangul_parsed,hangul_parsed_romaja,oldkana,multibyte_labeled_kana,multibyte_labeled_hangul].flatten
  extracted_records[[record[0],record[1]].join(',')] = output_record # DISTINCT

end

puts tsv_header.join(",")

extracted_records.each do |key,record|
  puts record.join(",")
end
